#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

In [ ]:
import numpy as np

#THE BASICS :

#initialize array

In [9]:
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [10]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [12]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)

dimension of a : 1
dimension of b : 2


In [13]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)

shape of a : (3,)
shape of b : (2, 4)


#Get  Type

In [15]:
print("a type is :",a.dtype)

a type is : int16


In [16]:
#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;

size of a : 3


In [17]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)


a item size : 2
total size is a: 6


#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

In [18]:
#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]

np.float64(4.2)

In [19]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);


row : [2.1]


In [20]:
#Get specific column[:,column]
print("column :",b[:,1])


column : [2. 3.]


In [21]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])


subset of specific row [3.  4.5]


In [22]:
#change element
b[1,2]=8
print(b)

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


In [23]:
b[:,2]=[9,4]
b

array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

# 3-d Example 

In [ ]:
c=np.array([
[  
    [1,2],[2,3]
],
[
    [5,6],[7,8]
]
])

In [25]:
type(c)

numpy.ndarray

In [26]:
c.ndim

3

In [27]:
c.shape

(2, 2, 2)

In [28]:
c.size

8

In [29]:
c.dtype

dtype('int64')

In [31]:
c.itemsize* c.size

64

In [ ]:
c

array([[[1, 2],
        [2, 3]],

       [[5, 6],
        [7, 8]]])

In [34]:
 #Get specific element (work outside in)
 print("specified element is:",c[0,0,1])

specified element is: 2


initializing Different types of array

In [ ]:
zm=np.zeros((3,4))


In [ ]:
np.ones((3,3),dtype="int16")